const newsList = [
  {
    id: 1,
    title: '주식시장 상승',
    summary: '오늘 주식시장이 크게 올랐습니다.',
    source: '경제신문',
    date: '2025-05-27',
    url: 'https://news.example.com/stock-up',
  },
  {
    id: 2,
    title: '금리 인상 발표',
    summary: '중앙은행이 금리를 인상했습니다.',
    source: '뉴스데일리',
    date: '2025-05-26',
    url: 'https://news.example.com/rate-increase',
  },
  {
    id: 3,
    title: '삼성전자 2분기 실적 깜짝 상승',
    summary: '삼성전자가 2분기 실적에서 시장 기대치를 크게 상회하며 반도체 회복세를 보이고 있습니다.',
    source: '한국경제',
    date: '2025-05-25',
    url: 'https://news.example.com/samsung-earnings',
  },
  {
    id: 4,
    title: '네이버 매출 감소 우려',
    summary: '네이버의 광고 매출이 전년 대비 감소하면서 투자자들의 우려가 커지고 있습니다.',
    source: '매일경제',
    date: '2025-05-24',
    url: 'https://news.example.com/naver-revenue',
  },
  {
    id: 5,
    title: 'SK하이닉스 AI 메모리 수요 급증',
    summary: 'SK하이닉스가 인공지능 서버용 메모리 수요 급증으로 3분기 실적 개선이 기대됩니다.',
    source: '서울경제',
    date: '2025-05-23',
    url: 'https://news.example.com/skhynix-ai',
  },
  {
    id: 6,
    title: '카카오 신사업 진출 발표',
    summary: '카카오가 커머스 사업 확장을 통해 새로운 성장 동력을 확보한다고 발표했습니다.',
    source: '조선일보',
    date: '2025-05-22',
    url: 'https://news.example.com/kakao-commerce',
  },
  {
    id: 7,
    title: 'LG전자 북미 가전 시장 1위 달성',
    summary: 'LG전자가 북미 프리미엄 가전 시장에서 점유율 1위를 기록하며 글로벌 경쟁력을 입증했습니다.',
    source: '한국일보',
    date: '2025-05-21',
    url: 'https://news.example.com/lg-premium',
  },
  {
    id: 8,
    title: '현대차 중국 판매 부진 지속',
    summary: '현대차의 중국 시장 판매량이 계속 감소하면서 글로벌 전략 재검토가 필요한 상황입니다.',
    source: '머니투데이',
    date: '2025-05-20',
    url: 'https://news.example.com/hyundai-china',
  },
  {
    id: 9,
    title: 'NAVER 클라우드 사업 호조',
    summary: '네이버 클라우드 플랫폼의 매출이 전년 대비 50% 증가하며 성장세를 이어가고 있습니다.',
    source: '이데일리',
    date: '2025-05-19',
    url: 'https://news.example.com/naver-cloud',
  },
  {
    id: 10,
    title: '삼성디스플레이 OLED 수주 확대',
    summary: '삼성디스플레이가 애플향 OLED 패널 공급량 확대로 실적 개선이 예상됩니다.',
    source: '전자신문',
    date: '2025-05-18',
    url: 'https://news.example.com/samsung-oled',
  },
  {
    id: 11,
    title: 'LG화학 배터리 사업 적자 확대',
    summary: 'LG화학의 배터리 사업부문 적자가 확대되면서 구조조정 필요성이 제기되고 있습니다.',
    source: '파이낸셜뉴스',
    date: '2025-05-17',
    url: 'https://news.example.com/lgchem-battery',
  },
  {
    id: 12,
    title: 'SK텔레콤 5G 가입자 급증',
    summary: 'SK텔레콤의 5G 가입자가 1000만명을 돌파하며 통신 서비스 매출 증가에 기여하고 있습니다.',
    source: '디지털타임스',
    date: '2025-05-16',
    url: 'https://news.example.com/skt-5g',
  },
  {
    id: 13,
    title: 'KT 클라우드 사업 투자 확대',
    summary: 'KT가 클라우드 사업에 대규모 투자를 발표하며 디지털 전환 사업을 강화하고 있습니다.',
    source: '비즈니스워치',
    date: '2025-05-15',
    url: 'https://news.example.com/kt-cloud',
  },
  {
    id: 14,
    title: '포스코홀딩스 철강 가격 하락 영향',
    summary: '글로벌 철강 가격 하락으로 포스코홀딩스의 2분기 실적에 부정적 영향이 예상됩니다.',
    source: '연합뉴스',
    date: '2025-05-14',
    url: 'https://news.example.com/posco-steel',
  },
  {
    id: 15,
    title: '셀트리온 바이오의약품 수출 호조',
    summary: '셀트리온의 바이오의약품 수출이 크게 증가하며 글로벌 시장 확대에 성공하고 있습니다.',
    source: '약업신문',
    date: '2025-05-13',
    url: 'https://news.example.com/celltrion-export',
  }
];

export function getAllNews() {
    return newsList;
}